/**
 * Weekly Summary - Core logic
 * Fetches Linear + GitHub data, parses check-ins, builds payload with stats.
 * Reference: Apollos/weekly-summary.js (logic only, no file copying)
 */

import { mkdirSync, existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type {
  Payload,
  RunSummaryResult,
  CheckIn,
  Stats,
  ReviewEntry,
} from "./types.js";
import { buildMarkdownSummary } from "./markdown.js";
import { dataCache } from "./cache.js";
import {
  RateLimitExhaustedError,
  coreRefusalCount,
  fetchWithRetry,
  peekCoreBudget,
} from "./github-api.js";
import {
  SearchBudgetError,
  searchRequest,
  type SearchPriority,
} from "./github-search.js";
import { getMostRecentSnapshot, localDateString } from "./daily-snapshot.js";
import {
  computeBusinessLatencyHours,
  findRequestedAt,
  median,
  parsePrRef,
  sumVolume,
  type TimelineEvent,
} from "./github-metrics.js";
import {
  GitHubGraphQLError,
  toleratedGapCount,
  fetchDefaultBranchCommits,
  fetchPrActivity,
  fetchPrCommits,
  fetchUserId,
  parseAnyPrRef,
  prKey,
  type PrRef as GqlPrRef,
} from "./github-graphql.js";

const SUMMARY_README = `# Weekly Work Summaries

Generated by weekly-summary. Each file is named by week-ending date (YYYY-MM-DD).
`;

const LINEAR_API_BASE = "https://api.linear.app/graphql";
const GITHUB_API_BASE = "https://api.github.com";

const LINEAR_USER_QUERY = `
  query GetViewer {
    viewer { id name email }
  }
`;

const LINEAR_COMPLETED_QUERY = `
  query GetCompletedIssues($assigneeId: ID, $completedAfter: DateTimeOrDuration!, $completedBefore: DateTimeOrDuration!, $after: String) {
    issues(filter: { assignee: { id: { eq: $assigneeId } }, completedAt: { gte: $completedAfter, lte: $completedBefore } }, first: 100, after: $after) {
      nodes { id identifier title state { name type } url completedAt project { name } }
      pageInfo { hasNextPage endCursor }
    }
  }
`;

/**
 * Every issue in the workspace completed during the window, with recent state
 * history attached. Linear has no filter for "who moved it to Done", so we pull
 * the window's completions and match the actor ourselves — closing out a ticket
 * assigned to someone else still counts as your completion.
 */
const LINEAR_COMPLETED_BY_ACTOR_QUERY = `
  query GetWindowCompletedIssues($completedAfter: DateTimeOrDuration!, $completedBefore: DateTimeOrDuration!, $after: String) {
    issues(filter: { completedAt: { gte: $completedAfter, lte: $completedBefore } }, first: 50, after: $after) {
      nodes {
        id identifier title state { name type } url completedAt project { name }
        assignee { id }
        history(first: 20) { nodes { createdAt actor { id } toState { type } } }
      }
      pageInfo { hasNextPage endCursor }
    }
  }
`;

/**
 * Projects you lead or belong to that moved to a completed status in the window.
 * Pulls the shipping context too (description, dates, issue counts) — a finished
 * project is a headline deliverable, not a one-line row.
 *
 * Counts come from Linear's own `scope`/`progress` rather than a nested issues
 * connection: paging issues inside projects both caps big projects at the page
 * size and blows the 10,000-complexity ceiling on a single query.
 */
const LINEAR_COMPLETED_PROJECTS_QUERY = `
  query GetCompletedProjects($userId: ID!, $completedAfter: DateTimeOrDuration!, $completedBefore: DateTimeOrDuration!, $after: String) {
    projects(filter: { completedAt: { gte: $completedAfter, lte: $completedBefore }, or: [{ lead: { id: { eq: $userId } } }, { members: { id: { eq: $userId } } }] }, first: 50, after: $after) {
      nodes {
        id name url description completedAt startedAt startDate targetDate
        scope progress
        status { name type }
        lead { id name }
      }
      pageInfo { hasNextPage endCursor }
    }
  }
`;

const LINEAR_WORKED_ON_QUERY = `
  query GetWorkedOnIssues($assigneeId: ID, $updatedAfter: DateTimeOrDuration!, $after: String) {
    issues(filter: { assignee: { id: { eq: $assigneeId } }, updatedAt: { gte: $updatedAfter } }, first: 100, after: $after) {
      nodes { id identifier title state { name type } url completedAt project { name } }
      pageInfo { hasNextPage endCursor }
    }
  }
`;

const LINEAR_CREATED_QUERY = `
  query GetCreatedIssues($creatorId: ID!, $createdAfter: DateTimeOrDuration!, $createdBefore: DateTimeOrDuration!, $after: String) {
    issues(filter: { creator: { id: { eq: $creatorId } }, createdAt: { gte: $createdAfter, lte: $createdBefore } }, first: 100, after: $after) {
      nodes { id identifier title state { name type } url createdAt project { name } }
      pageInfo { hasNextPage endCursor }
    }
  }
`;

const LINEAR_COMMENTS_QUERY = `
  query GetUserComments($userId: ID!, $createdAfter: DateTimeOrDuration!, $createdBefore: DateTimeOrDuration!, $after: String) {
    comments(filter: { user: { id: { eq: $userId } }, createdAt: { gte: $createdAfter, lte: $createdBefore } }, first: 100, after: $after) {
      nodes {
        id
        createdAt
        issue { id identifier title url state { name type } project { name } }
      }
      pageInfo { hasNextPage endCursor }
    }
  }
`;

/**
 * Local midnight for the calendar day of `now`.
 */
export function startOfLocalDay(now: Date): Date {
  return new Date(now.getFullYear(), now.getMonth(), now.getDate(), 0, 0, 0, 0);
}

/**
 * Resolve the Today window as capture-to-capture:
 * - Live view: since the most recent capture → now
 * - Capture / re-capture: since the previous day's capture → now
 *   (so updating today's snapshot refreshes the full open period)
 * Falls back to local midnight when there is no prior capture.
 */
export function resolveTodayWindow(
  now: Date,
  options: { forCapture?: boolean } = {}
): { windowStart: Date; windowEnd: Date } {
  const windowEnd = now;
  const today = localDateString(now);

  if (options.forCapture) {
    const prev = getMostRecentSnapshot(today);
    if (prev) {
      return { windowStart: prev.capturedAt, windowEnd };
    }
    return { windowStart: startOfLocalDay(now), windowEnd };
  }

  const latest = getMostRecentSnapshot();
  if (latest) {
    return { windowStart: latest.capturedAt, windowEnd };
  }
  return { windowStart: startOfLocalDay(now), windowEnd };
}

export function getWindowStart(
  now: Date,
  todayMode: boolean,
  yesterdayMode = false
): Date {
  if (yesterdayMode) {
    const yesterday = new Date(now);
    yesterday.setDate(now.getDate() - 1);
    return startOfLocalDay(yesterday);
  }
  if (todayMode) {
    // Prefer resolveTodayWindow for capture-to-capture; this remains the
    // calendar-day fallback used by weekly math and tests.
    return startOfLocalDay(now);
  }
  const day = now.getDay();
  const daysSinceSaturday = (day + 1) % 7;
  const saturday = new Date(now);
  saturday.setDate(now.getDate() - daysSinceSaturday);
  saturday.setHours(0, 0, 0, 0);
  return saturday;
}

export function getWindowEnd(
  now: Date,
  todayMode = false,
  yesterdayMode = false
): Date {
  if (yesterdayMode) {
    const yesterday = new Date(now);
    yesterday.setDate(now.getDate() - 1);
    return new Date(
      yesterday.getFullYear(),
      yesterday.getMonth(),
      yesterday.getDate(),
      23,
      59,
      59,
      999
    );
  }
  if (todayMode) {
    return now;
  }
  return new Date(
    now.getFullYear(),
    now.getMonth(),
    now.getDate(),
    23,
    59,
    59,
    999
  );
}

/**
 * Full Sat–Fri window for a Friday week-ending date (YYYY-MM-DD).
 */
export function getWindowForWeekEnding(weekEnding: string): {
  windowStart: Date;
  windowEnd: Date;
} {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(weekEnding)) {
    throw new Error(
      `Invalid week-ending date: ${weekEnding} (expected YYYY-MM-DD)`
    );
  }
  const [y, m, d] = weekEnding.split("-").map(Number);
  const windowEnd = new Date(y, m - 1, d, 23, 59, 59, 999);
  if (Number.isNaN(windowEnd.getTime())) {
    throw new Error(`Invalid week-ending date: ${weekEnding}`);
  }
  if (windowEnd.getDay() !== 5) {
    const dayName = windowEnd.toLocaleDateString("en-US", { weekday: "long" });
    throw new Error(
      `--week must be a Friday (week-ending date). Got ${weekEnding} (${dayName}).`
    );
  }
  const windowStart = new Date(y, m - 1, d - 6, 0, 0, 0, 0);
  return { windowStart, windowEnd };
}

export function parseCheckIns(checkInsText: string): CheckIn[] {
  if (!checkInsText?.trim()) return [];

  const skipPatterns = [
    /^Apollos Engineering:/i,
    /^Nathan Lewis/i,
    /^File…/,
    /^PR Reviews?$/i,
    /^> /,
  ];

  const isSkipLine = (line: string) => {
    const t = line.trim();
    if (!t) return true;
    return skipPatterns.some((p) => p.test(t));
  };

  const lines = checkInsText.split("\n");
  const entries: CheckIn[] = [];
  let currentDay: string | null = null;
  let currentContent: string[] = [];

  const dayRegex =
    /^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday|Yesterday|Dec \d+|December \d+)[:.]?\s*(.*)$/i;

  for (const line of lines) {
    if (isSkipLine(line)) continue;

    const m = line.match(dayRegex);
    if (m) {
      if (currentDay && currentContent.length > 0) {
        const content = currentContent.join("\n").trim();
        if (content) entries.push({ day: currentDay, content });
      }
      currentDay = m[1];
      currentContent = m[2]?.trim() ? [m[2].trim()] : [];
    } else if (currentDay && !isSkipLine(line)) {
      currentContent.push(line);
    }
  }

  if (currentDay && currentContent.length > 0) {
    const content = currentContent.join("\n").trim();
    if (content) entries.push({ day: currentDay, content });
  }

  return entries.length > 0
    ? entries
    : [{ day: "Check-ins", content: checkInsText.trim() }];
}

async function fetchLinearPage(
  headers: Record<string, string>,
  query: string,
  variables: Record<string, unknown>
) {
  const res = await fetch(LINEAR_API_BASE, {
    method: "POST",
    headers,
    body: JSON.stringify({ query, variables }),
  });
  if (!res.ok) throw new Error(`Linear API: ${res.status}`);
  const data = await res.json();
  if (data.errors) throw new Error(`Linear: ${JSON.stringify(data.errors)}`);
  return data.data;
}

type LinearIssueNode = {
  id?: string;
  identifier?: string;
  title?: string;
  url?: string | null;
  state?: { name?: string; type?: string };
  completedAt?: string | null;
  createdAt?: string | null;
  project?: { name?: string } | null;
  assignee?: { id?: string } | null;
  history?: {
    nodes?: Array<{
      createdAt?: string;
      actor?: { id?: string } | null;
      toState?: { type?: string } | null;
    }>;
  };
};

type LinearProjectNode = {
  id?: string;
  name?: string;
  url?: string | null;
  description?: string | null;
  completedAt?: string | null;
  startedAt?: string | null;
  startDate?: string | null;
  targetDate?: string | null;
  status?: { name?: string; type?: string } | null;
  lead?: { id?: string; name?: string } | null;
  /** Total countable issues in the project, per Linear. */
  scope?: number | null;
  /** Fraction of scope completed (0–1). */
  progress?: number | null;
};

async function fetchAllLinearIssues(
  headers: Record<string, string>,
  query: string,
  variables: Record<string, unknown>
) {
  const all: unknown[] = [];
  let after: string | null = null;
  const base = { ...variables };
  do {
    const vars = { ...base, after };
    const data = await fetchLinearPage(headers, query, vars);
    const conn = (
      data as {
        issues?: {
          nodes: unknown[];
          pageInfo?: { hasNextPage?: boolean; endCursor?: string };
        };
      }
    )?.issues;
    if (!conn?.nodes) break;
    all.push(...conn.nodes);
    if (!conn.pageInfo?.hasNextPage) break;
    after = conn.pageInfo?.endCursor ?? null;
  } while (after !== null);
  return all as LinearIssueNode[];
}

async function fetchAllLinearProjects(
  headers: Record<string, string>,
  query: string,
  variables: Record<string, unknown>
): Promise<LinearProjectNode[]> {
  const all: LinearProjectNode[] = [];
  let after: string | null = null;
  const base = { ...variables };
  do {
    const vars = { ...base, after };
    const data = await fetchLinearPage(headers, query, vars);
    const conn = (
      data as {
        projects?: {
          nodes: LinearProjectNode[];
          pageInfo?: { hasNextPage?: boolean; endCursor?: string };
        };
      }
    )?.projects;
    if (!conn?.nodes) break;
    all.push(...conn.nodes);
    if (!conn.pageInfo?.hasNextPage) break;
    after = conn.pageInfo?.endCursor ?? null;
  } while (after !== null);
  return all;
}

/**
 * Runs one Linear sub-query, degrading to an empty list on failure.
 * Without this a single rejected query (complexity, rate limit, a schema change)
 * takes down every Linear stat at once and the summary quietly reports zeros.
 */
async function softFetchLinear<T>(
  label: string,
  fetcher: () => Promise<T[]>
): Promise<T[]> {
  try {
    return await fetcher();
  } catch (err) {
    console.error(
      `⚠️  Linear ${label} query failed: ${(err as Error).message}`
    );
    return [];
  }
}

/**
 * Project statuses that close a project without delivering it. Linear types these
 * as `completed` (so completedAt gets set) even though nothing shipped — this
 * workspace has both "Complete" and "Incomplete" under that type, and only the
 * former counts as done.
 */
const UNDELIVERED_PROJECT_STATUS =
  /^(incomplete|cancell?ed|abandoned|won'?t\s*do)$/i;

/** True when the project's status means it actually shipped, not just closed. */
export function isDeliveredProject(project: {
  status?: { name?: string; type?: string } | null;
}): boolean {
  const type = project.status?.type;
  if (type && type !== "completed") return false;
  const name = project.status?.name?.trim();
  // No custom status vocabulary — completedAt is the only signal available.
  if (!name) return true;
  return !UNDELIVERED_PROJECT_STATUS.test(name);
}

/**
 * The user who made the issue's most recent move into a completed state.
 * History comes back newest-first, so the first completed transition is the latest.
 * Returns null when that transition isn't in the fetched history (or had no actor).
 */
function completedByActorId(
  issue: LinearIssueNode,
  windowStart: Date,
  windowEnd: Date
): string | null {
  const entry = (issue.history?.nodes ?? []).find(
    (h) => h.toState?.type === "completed"
  );
  if (!entry?.createdAt || !entry.actor?.id) return null;
  const at = new Date(entry.createdAt);
  if (at < windowStart || at > windowEnd) return null;
  return entry.actor.id;
}

type LinearComment = {
  id: string;
  createdAt: string;
  issue?: {
    id?: string;
    identifier?: string;
    title?: string;
    url?: string;
    state?: { name?: string; type?: string };
    project?: { name?: string };
  };
};

async function fetchAllLinearComments(
  headers: Record<string, string>,
  query: string,
  variables: Record<string, unknown>
): Promise<LinearComment[]> {
  const all: LinearComment[] = [];
  let after: string | null = null;
  const base = { ...variables };
  do {
    const vars = { ...base, after };
    const data = await fetchLinearPage(headers, query, vars);
    const conn = (
      data as {
        comments?: {
          nodes: LinearComment[];
          pageInfo?: { hasNextPage?: boolean; endCursor?: string };
        };
      }
    )?.comments;
    if (!conn?.nodes) break;
    all.push(...conn.nodes);
    if (!conn.pageInfo?.hasNextPage) break;
    after = conn.pageInfo?.endCursor ?? null;
  } while (after !== null);
  return all;
}

async function fetchLinearData(
  windowStart: Date,
  windowEnd: Date,
  windowStartISO: string,
  windowEndISO: string
) {
  const key = process.env.LINEAR_API_KEY;
  if (!key)
    return {
      completedIssues: [],
      completedProjects: [],
      workedOnIssues: [],
      createdIssues: [],
      commentedIssues: [],
      userName: null,
    };

  const headers = { Authorization: key, "Content-Type": "application/json" };

  try {
    const userData = await fetchLinearPage(headers, LINEAR_USER_QUERY, {});
    const userId = (userData as { viewer?: { id?: string; name?: string } })
      ?.viewer?.id;
    if (!userId) throw new Error("No Linear user ID");

    const userName =
      (userData as { viewer?: { name?: string } })?.viewer?.name ?? null;

    const [
      assignedCompleted,
      windowCompleted,
      completedProjects,
      rawWorkedOn,
      createdIssues,
      rawComments,
    ] = await Promise.all([
      softFetchLinear("assigned completed issues", () =>
        fetchAllLinearIssues(headers, LINEAR_COMPLETED_QUERY, {
          assigneeId: userId,
          completedAfter: windowStartISO,
          completedBefore: windowEndISO,
        })
      ),
      softFetchLinear("issues completed in window", () =>
        fetchAllLinearIssues(headers, LINEAR_COMPLETED_BY_ACTOR_QUERY, {
          completedAfter: windowStartISO,
          completedBefore: windowEndISO,
        })
      ),
      softFetchLinear("completed projects", () =>
        fetchAllLinearProjects(headers, LINEAR_COMPLETED_PROJECTS_QUERY, {
          userId,
          completedAfter: windowStartISO,
          completedBefore: windowEndISO,
        })
      ),
      softFetchLinear("worked-on issues", () =>
        fetchAllLinearIssues(headers, LINEAR_WORKED_ON_QUERY, {
          assigneeId: userId,
          updatedAfter: windowStartISO,
        })
      ),
      softFetchLinear("created issues", () =>
        fetchAllLinearIssues(headers, LINEAR_CREATED_QUERY, {
          creatorId: userId,
          createdAfter: windowStartISO,
          createdBefore: windowEndISO,
        })
      ),
      softFetchLinear("comments", () =>
        fetchAllLinearComments(headers, LINEAR_COMMENTS_QUERY, {
          userId,
          createdAfter: windowStartISO,
          createdBefore: windowEndISO,
        })
      ),
    ]);

    // Only projects that actually shipped — "Incomplete" is a completed-type
    // status in Linear, so completedAt alone would count abandoned work.
    const deliveredProjects = completedProjects.filter(isDeliveredProject);

    // Issues you moved to Done yourself, whoever they were assigned to.
    const seenCompletedIds = new Set(
      assignedCompleted.map((i) => i.id).filter(Boolean) as string[]
    );
    const completedIssues = [
      ...assignedCompleted,
      ...windowCompleted.filter((issue) => {
        if (issue.id && seenCompletedIds.has(issue.id)) return false;
        return completedByActorId(issue, windowStart, windowEnd) === userId;
      }),
    ];

    const workedOnIssues = rawWorkedOn.filter((issue) => {
      const stateName = issue.state?.name ?? "";
      const stateType = issue.state?.type ?? "";
      const completedAt = issue.completedAt
        ? new Date(issue.completedAt)
        : null;
      if (stateName === "In Progress" || stateName === "In Review") return true;
      if (stateName === "Done" || stateType === "completed") {
        if (!completedAt) return false;
        return completedAt >= windowStart && completedAt <= windowEnd;
      }
      return false;
    });

    const seenIssueIds = new Set<string>();
    const commentedIssues = rawComments
      .filter((c) => {
        const issueId = c.issue?.id;
        if (!issueId || seenIssueIds.has(issueId)) return false;
        seenIssueIds.add(issueId);
        return true;
      })
      .map((c) => ({
        identifier: c.issue?.identifier ?? "",
        title: c.issue?.title ?? "",
        url: c.issue?.url ?? null,
        project: c.issue?.project?.name ?? null,
        state: c.issue?.state?.name ?? c.issue?.state?.type ?? null,
      }));

    return {
      completedIssues,
      completedProjects: deliveredProjects,
      workedOnIssues,
      createdIssues,
      commentedIssues,
      userName,
    };
  } catch {
    return {
      completedIssues: [],
      completedProjects: [],
      workedOnIssues: [],
      createdIssues: [],
      commentedIssues: [],
      userName: null,
    };
  }
}

/**
 * GitHub search returns at most 100 items per page. A single unpaginated
 * request silently truncates: a week with 200 reviewed PRs came back as 100
 * candidates, so the review count was capped at whatever survived filtering.
 * Page until the result set is exhausted, bounded by the 1,000-result ceiling
 * the search API enforces.
 */
const SEARCH_PAGE_SIZE = 100;
const SEARCH_MAX_PAGES = 10;

async function searchAllIssues(
  query: string,
  headers: HeadersInit,
  priority: SearchPriority
): Promise<Array<Record<string, unknown>>> {
  const items: Array<Record<string, unknown>> = [];
  for (let page = 1; page <= SEARCH_MAX_PAGES; page += 1) {
    const res = await searchRequest(
      `${GITHUB_API_BASE}/search/issues?q=${query}&per_page=${SEARCH_PAGE_SIZE}&page=${page}`,
      headers,
      { priority }
    );
    if (!res.ok) break;
    const data = (await res.json()) as {
      items?: Array<Record<string, unknown>>;
      total_count?: number;
    };
    const batch = data.items ?? [];
    items.push(...batch);
    if (batch.length < SEARCH_PAGE_SIZE) break;
    if (
      typeof data.total_count === "number" &&
      items.length >= data.total_count
    )
      break;
  }
  return items;
}

/**
 * `updated:A..B` — bounding both ends keeps the result set under the search
 * API's 1,000-result ceiling. A review always bumps the PR's updated_at, so a
 * PR reviewed inside the window was updated inside it too. Bounds come from the
 * UTC dates, which only ever widens the range; exact timestamps are filtered
 * afterwards.
 */
function dateRange(startISO: string, endISO: string): string {
  return `${startISO.split("T")[0]}..${endISO.split("T")[0]}`;
}

function filterApollosPRs(items: Array<{ html_url?: string }>) {
  return (items ?? []).filter((pr) => pr.html_url?.includes("ApollosProject"));
}

type CandidateReviewPR = {
  pull_request?: { url?: string };
  html_url?: string;
  title?: string;
  [k: string]: unknown;
};

export type ReviewedPR = CandidateReviewPR & {
  reviewed_at: string;
  review_state: string;
};

/**
 * GitHub applies a secondary rate limit to concurrent requests, and these fans
 * are now per-candidate over a fully paginated search — up to a thousand PRs.
 * Firing them all at once earns a wall of 403s, which this code reads as "no
 * review found" and silently turns into a zero. Bound the burst instead.
 */
const GITHUB_FETCH_CONCURRENCY = 6;

async function mapWithConcurrency<T, R>(
  items: T[],
  limit: number,
  fn: (item: T) => Promise<R>
): Promise<R[]> {
  const results = new Array<R>(items.length);
  let next = 0;
  const workers = Array.from(
    { length: Math.min(limit, items.length) },
    async () => {
      while (next < items.length) {
        const i = next++;
        results[i] = await fn(items[i]!);
      }
    }
  );
  await Promise.all(workers);
  return results;
}

/**
 * Keeps only PRs where the user submitted a review (comment, request changes, or approve) within the time window.
 * Attaches reviewed_at (first non-PENDING submitted_at by user in window) and review_state.
 */
async function filterReviewsBySubmittedInWindow(
  candidatePRs: CandidateReviewPR[],
  windowStart: Date,
  windowEnd: Date,
  username: string,
  headers: HeadersInit
): Promise<ReviewedPR[]> {
  const results = await mapWithConcurrency(
    candidatePRs,
    GITHUB_FETCH_CONCURRENCY,
    async (pr) => {
      // per_page matters: unpaginated this returns GitHub's default first 30
      // reviews, and a PR with more than that (one had 167) hid the user's own
      // review behind the page boundary and reported it as never reviewed.
      const reviewsUrl = pr.pull_request?.url
        ? `${pr.pull_request.url}/reviews?per_page=100`
        : null;
      if (!reviewsUrl) return null;
      try {
        const res = await fetchWithRetry(reviewsUrl, { headers });
        if (!res.ok) return null;
        const reviews = (await res.json()) as Array<{
          user?: { login?: string };
          state?: string;
          submitted_at?: string | null;
        }>;
        const mine = reviews
          .filter(
            (r) =>
              r.user?.login === username &&
              r.submitted_at != null &&
              r.state !== "PENDING" &&
              new Date(r.submitted_at) >= windowStart &&
              new Date(r.submitted_at) <= windowEnd
          )
          .sort(
            (a, b) =>
              new Date(a.submitted_at!).getTime() -
              new Date(b.submitted_at!).getTime()
          );
        const first = mine[0];
        if (!first?.submitted_at) return null;
        return {
          ...pr,
          reviewed_at: first.submitted_at,
          review_state: first.state ?? "COMMENTED",
        };
      } catch {
        return null;
      }
    }
  );
  return results.filter((pr): pr is ReviewedPR => pr != null);
}

/**
 * Fetch issue timeline and return earliest review_requested for username
 * that precedes reviewedAt. Null for drive-by reviews.
 */
async function fetchRequestedAt(
  htmlUrl: string | undefined,
  username: string,
  reviewedAt: string,
  headers: HeadersInit
): Promise<string | null> {
  const ref = parsePrRef(htmlUrl);
  if (!ref) return null;
  const url = `https://api.github.com/repos/${ref.owner}/${ref.repo}/issues/${ref.number}/timeline?per_page=100`;
  try {
    const res = await fetchWithRetry(url, {
      headers: {
        ...(headers as Record<string, string>),
        Accept: "application/vnd.github.mockingbird-preview+json",
      },
    });
    if (!res.ok) return null;
    const events = (await res.json()) as TimelineEvent[];
    return findRequestedAt(events, username, reviewedAt);
  } catch {
    return null;
  }
}

async function enrichReviewsWithLatency(
  reviews: ReviewedPR[],
  username: string,
  headers: HeadersInit
): Promise<ReviewEntry[]> {
  return mapWithConcurrency(reviews, GITHUB_FETCH_CONCURRENCY, async (pr) => {
    const ref = parsePrRef(pr.html_url);
    const requested_at = await fetchRequestedAt(
      pr.html_url,
      username,
      pr.reviewed_at,
      headers
    );
    return {
      title: pr.title ?? "",
      url: pr.html_url ?? "",
      repo: ref?.repo ?? null,
      requested_at,
      reviewed_at: pr.reviewed_at,
      review_state: pr.review_state,
      latency_hours: computeBusinessLatencyHours(requested_at, pr.reviewed_at),
    };
  });
}

/** Earliest non-PENDING review by the user inside the window. */
function earliestReviewInWindow(
  reviews: Array<{ state: string; submittedAt: string | null }>,
  windowStart: Date,
  windowEnd: Date
): { submittedAt: string; state: string } | null {
  const mine = reviews
    .filter(
      (r) =>
        r.submittedAt != null &&
        r.state !== "PENDING" &&
        new Date(r.submittedAt) >= windowStart &&
        new Date(r.submittedAt) <= windowEnd
    )
    .sort(
      (a, b) =>
        new Date(a.submittedAt!).getTime() - new Date(b.submittedAt!).getTime()
    );
  const first = mine[0];
  return first ? { submittedAt: first.submittedAt!, state: first.state } : null;
}

function toReviewEntry(
  pr: CandidateReviewPR,
  reviewed: { submittedAt: string; state: string },
  requested_at: string | null
): ReviewEntry {
  const ref = parsePrRef(pr.html_url);
  return {
    title: pr.title ?? "",
    url: pr.html_url ?? "",
    repo: ref?.repo ?? null,
    requested_at,
    reviewed_at: reviewed.submittedAt,
    review_state: reviewed.state,
    latency_hours: computeBusinessLatencyHours(
      requested_at,
      reviewed.submittedAt
    ),
  };
}

/**
 * In-window reviews, latency-enriched, for a candidate set.
 *
 * This replaces two REST fans — one request per candidate for `/reviews`, a
 * second for `/timeline` — with a batched GraphQL read, which is the difference
 * between ~570 requests for a busy week and ~20. The filtering is deliberately
 * the same logic and the same helpers the REST path used; only the transport
 * changed. A PR GraphQL could not answer for, or returned more than one page
 * for, falls back to the REST path rather than risk a short count.
 */
async function buildReviewEntries(
  candidatePRs: CandidateReviewPR[],
  windowStart: Date,
  windowEnd: Date,
  username: string,
  headers: HeadersInit
): Promise<ReviewEntry[]> {
  const paired = candidatePRs.map((pr) => ({
    pr,
    ref: parseAnyPrRef(pr.html_url ?? pr.pull_request?.url),
  }));

  const activity = await fetchPrActivity(
    paired.map((x) => x.ref).filter((r): r is GqlPrRef => r != null),
    username,
    headers,
    { reviews: true, reviewRequests: true }
  );

  const entries: ReviewEntry[] = [];
  const needsRest: CandidateReviewPR[] = [];

  for (const { pr, ref } of paired) {
    const act = ref ? activity.get(prKey(ref)) : undefined;
    if (!act || act.truncated.reviews) {
      if (pr.pull_request?.url) needsRest.push(pr);
      continue;
    }
    const reviewed = earliestReviewInWindow(act.reviews, windowStart, windowEnd);
    if (!reviewed) continue;
    const events: TimelineEvent[] = act.reviewRequests.map((r) => ({
      event: "review_requested",
      created_at: r.createdAt,
      requested_reviewer: r.login ? { login: r.login } : null,
    }));
    entries.push(
      toReviewEntry(
        pr,
        reviewed,
        findRequestedAt(events, username, reviewed.submittedAt)
      )
    );
  }

  if (needsRest.length > 0) {
    const reviewed = await filterReviewsBySubmittedInWindow(
      needsRest,
      windowStart,
      windowEnd,
      username,
      headers
    );
    entries.push(
      ...(await enrichReviewsWithLatency(reviewed, username, headers))
    );
  }

  return entries;
}

function getCommitRepos(): { owner: string; repos: string[] } {
  const owner = process.env.GITHUB_ORG ?? "ApollosProject";
  const raw =
    process.env.GITHUB_COMMIT_REPOS ??
    "apollos-admin,apollos-cluster,apollos-giving-performance-qa,apollos-platforms,git-for-sql,freedup-migration";
  const repos = raw
    .split(",")
    .map((r) => r.trim())
    .filter(Boolean);
  return { owner, repos };
}

type PrRef = { repo: string; number: number };

/**
 * Count commits authored by `username` within the window across:
 *   1. The default branch of each configured repo (`/repos/.../commits`)
 *   2. Every branch attached to one of the user's PRs (open, draft, or merged)
 *      via `/repos/.../pulls/{n}/commits`
 *
 * Commits are deduped by SHA so a commit that exists on both a PR branch and
 * the default branch (after merge) is only counted once.
 */
async function fetchCommitsPushed(
  username: string,
  headers: Record<string, string>,
  windowStart: Date,
  windowEnd: Date,
  userPRs: PrRef[]
): Promise<{ total: number; reposWithCommits: string[] }> {
  const { owner, repos } = getCommitRepos();
  const trackedRepos = new Set(repos);
  if (repos.length === 0) return { total: 0, reposWithCommits: [] };

  const since = windowStart.toISOString();
  const until = windowEnd.toISOString();

  const seen = new Map<string, string>(); // sha -> repo

  const inWindow = (iso?: string | null): boolean => {
    if (!iso) return false;
    const t = new Date(iso).getTime();
    return t >= windowStart.getTime() && t <= windowEnd.getTime();
  };

  try {
    // Both halves of this were a paginated REST request per repo and per PR —
    // ~90 requests, and the last thing in a weekly run still drawing on the
    // core budget. Batched over GraphQL they are a handful.
    const authorId = await fetchUserId(username, headers);
    if (!authorId) throw new Error(`no GitHub user for login ${username}`);

    const [defaultBranch, prCommits] = await Promise.all([
      fetchDefaultBranchCommits(owner, repos, authorId, since, until, headers),
      fetchPrCommits(
        userPRs
          .filter((p) => trackedRepos.has(p.repo))
          .map((p) => ({ owner, repo: p.repo, number: p.number })),
        headers
      ),
    ]);

    for (const [repo, commits] of defaultBranch) {
      for (const c of commits) {
        if (!seen.has(c.oid)) seen.set(c.oid, repo);
      }
    }

    for (const p of userPRs) {
      if (!trackedRepos.has(p.repo)) continue;
      const commits = prCommits.get(prKey({ owner, repo: p.repo, number: p.number }));
      for (const c of commits ?? []) {
        // The REST path bounded PR commits on commit.author.date; keep that.
        if (!inWindow(c.authoredDate ?? c.committedDate)) continue;
        // Same author match as the REST path: the linked account, or an
        // email/name carrying the username for unlinked commits.
        const matchesUser =
          c.login === username ||
          c.email?.toLowerCase().includes(username.toLowerCase()) ||
          c.name?.toLowerCase().includes(username.toLowerCase());
        if (!matchesUser) continue;
        if (!seen.has(c.oid)) seen.set(c.oid, p.repo);
      }
    }

    const total = seen.size;
    const reposWithCommits = [...new Set([...seen.values()])].sort();
    return { total, reposWithCommits };
  } catch (err) {
    // "We could not ask" is not "you pushed nothing". This catch used to return
    // a zero for every failure, which is how an exhausted GraphQL budget was
    // saved as commits_pushed: 0 next to 140 real commits.
    if (
      err instanceof GitHubGraphQLError ||
      err instanceof RateLimitExhaustedError
    ) {
      throw err;
    }
    return { total: 0, reposWithCommits: [] };
  }
}

const COMMENT_PAGE_SIZE = 100;

/** Issue comments left by `username` on one PR, bounded to the window at both ends. */
async function countMyComments(
  commentsUrl: string,
  username: string,
  windowStart: Date,
  windowEnd: Date,
  headers: HeadersInit
): Promise<number> {
  let total = 0;
  let page = 1;
  try {
    while (true) {
      const sep = commentsUrl.includes("?") ? "&" : "?";
      const res = await fetchWithRetry(
        `${commentsUrl}${sep}per_page=${COMMENT_PAGE_SIZE}&page=${page}`,
        { headers }
      );
      if (!res.ok) return total;
      const comments = (await res.json()) as Array<{
        user?: { login?: string };
        created_at?: string;
      }>;
      if (!Array.isArray(comments)) return total;
      for (const c of comments) {
        if (c.user?.login !== username || c.created_at == null) continue;
        const at = new Date(c.created_at);
        if (at >= windowStart && at <= windowEnd) total += 1;
      }
      if (comments.length < COMMENT_PAGE_SIZE) return total;
      page += 1;
    }
  } catch {
    return total;
  }
}

/**
 * Reviews the user submitted inside a window, latency-enriched — the same
 * pipeline the live weekly run uses. Exported so backfills of saved summaries
 * recompute from identical logic rather than a second implementation that can
 * drift.
 */
export async function fetchReviewsInWindow(
  windowStart: Date,
  windowEnd: Date,
  username: string,
  headers: HeadersInit,
  options: { searchUntil?: Date } = {}
): Promise<ReviewEntry[]> {
  // Backfills widen the *search* bound (a PR reviewed in-window can be updated
  // long after it) while the submitted_at filter below stays on the real window.
  const searchUntil = options.searchUntil ?? windowEnd;
  const items = await searchAllIssues(
    `reviewed-by:${username}+type:pr+updated:${dateRange(
      windowStart.toISOString(),
      searchUntil.toISOString()
    )}`,
    headers,
    "high"
  );
  return buildReviewEntries(
    filterApollosPRs(items),
    windowStart,
    windowEnd,
    username,
    headers
  );
}

/** PRs the user authored that were created or touched on or after the window's start day. */
export async function searchAuthoredPRs(
  windowStart: Date,
  windowEnd: Date,
  username: string,
  headers: HeadersInit
): Promise<Array<Record<string, unknown>>> {
  const range = dateRange(windowStart.toISOString(), windowEnd.toISOString());
  const [created, updated] = await Promise.all([
    searchAllIssues(
      `author:${username}+type:pr+created:${range}`,
      headers,
      "high"
    ),
    searchAllIssues(
      `author:${username}+type:pr+updated:${range}`,
      headers,
      "high"
    ),
  ]);
  const seen = new Set<string>();
  return [...created, ...updated].filter((pr) => {
    const url = pr.html_url as string | undefined;
    if (!url || seen.has(url)) return false;
    seen.add(url);
    return url.includes("ApollosProject");
  });
}

/**
 * Issue comments by the user, across every given PR, bounded to the window.
 *
 * Batched over GraphQL — this was one paginated REST request per PR, ~290 for a
 * busy week. Accepts any PR-identifying URL (html_url, or an API pulls/issues
 * url) so both the live run and the backfill script can hand it what they have.
 * Anything unparseable, or with more than one page of comments, is counted the
 * old way so the total cannot come up short.
 */
export async function countPrCommentsInWindow(
  commentsUrls: string[],
  username: string,
  windowStart: Date,
  windowEnd: Date,
  headers: HeadersInit
): Promise<number> {
  // Dedup on PR identity, not on the URL string: callers hand us a mix of
  // html_urls and API comments_urls, which are different strings for the same
  // PR, and one you both authored and reviewed arrives as both. Counting it
  // twice would inflate the total.
  const byPr = new Map<string, { url: string; ref: GqlPrRef | null }>();
  for (const url of commentsUrls.filter(Boolean)) {
    const ref = parseAnyPrRef(url);
    const key = ref ? prKey(ref) : `url:${url}`;
    if (!byPr.has(key)) byPr.set(key, { url, ref });
  }
  const paired = [...byPr.values()];

  const activity = await fetchPrActivity(
    paired.map((x) => x.ref).filter((r): r is GqlPrRef => r != null),
    username,
    headers,
    { comments: true }
  );

  let total = 0;
  const needsRest: string[] = [];

  for (const { url, ref } of paired) {
    const act = ref ? activity.get(prKey(ref)) : undefined;
    if (!act || act.truncated.comments) {
      needsRest.push(url);
      continue;
    }
    for (const c of act.comments) {
      if (c.login !== username) continue;
      const at = new Date(c.createdAt);
      if (at >= windowStart && at <= windowEnd) total += 1;
    }
  }

  if (needsRest.length > 0) {
    const counts = await mapWithConcurrency(
      needsRest,
      GITHUB_FETCH_CONCURRENCY,
      (url) =>
        countMyComments(
          commentsUrlFor(url),
          username,
          windowStart,
          windowEnd,
          headers
        )
    );
    total += counts.reduce((a, b) => a + b, 0);
  }

  return total;
}

/** The REST fallback needs a comments endpoint; callers may pass any PR url. */
function commentsUrlFor(url: string): string {
  if (url.includes("/comments")) return url;
  const ref = parseAnyPrRef(url);
  if (!ref) return url;
  return `${GITHUB_API_BASE}/repos/${ref.owner}/${ref.repo}/issues/${ref.number}/comments`;
}

async function fetchGitHubData(
  windowStart: Date,
  windowStartISO: string,
  windowEnd: Date
) {
  const token = process.env.GITHUB_TOKEN;
  const username = process.env.GITHUB_USERNAME ?? "nlewis84";
  if (!token)
    return {
      prs: [],
      reviews: [],
      comments: 0,
      commits_pushed: 0,
      reposWithCommits: [],
    };

  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
  };
  try {
    // "high": these three are what the page exists to show, so they keep the
    // smallest reserve and the monthly search yields to them.
    const range = dateRange(windowStartISO, windowEnd.toISOString());
    const [prsCreatedItems, prsUpdatedItems, reviewItems] = await Promise.all([
      searchAllIssues(
        `author:${username}+type:pr+created:${range}`,
        headers,
        "high"
      ),
      searchAllIssues(
        `author:${username}+type:pr+updated:${range}`,
        headers,
        "high"
      ),
      searchAllIssues(
        `reviewed-by:${username}+type:pr+updated:${range}`,
        headers,
        "high"
      ),
    ]);

    const allPRs = [...prsCreatedItems, ...prsUpdatedItems];
    const seen = new Set<string>();
    const uniquePRs = allPRs.filter((pr: { html_url?: string }) => {
      if (!pr.html_url || seen.has(pr.html_url)) return false;
      seen.add(pr.html_url);
      return pr.html_url.includes("ApollosProject");
    });

    // One batched read instead of an unbounded `Promise.all` of one
    // `/pulls/:number` request per PR — which was both ~90 requests and the
    // only fan here with no concurrency limit.
    const detailActivity = await fetchPrActivity(
      uniquePRs
        .map((pr: { html_url?: string }) => parseAnyPrRef(pr.html_url))
        .filter((r): r is GqlPrRef => r != null),
      username,
      headers,
      { details: true }
    );

    const prDetails = uniquePRs.map(
      (pr: {
        pull_request?: { url?: string };
        html_url?: string;
        merged_at?: string;
        state?: string;
        additions?: number;
        deletions?: number;
        changed_files?: number;
      }) => {
        const ref = parseAnyPrRef(pr.html_url);
        const details = ref ? detailActivity.get(prKey(ref))?.details : null;
        return details ? { ...pr, ...details } : pr;
      }
    );

    const userPrRefs: PrRef[] = prDetails
      .map((pr: { html_url?: string }) => {
        const m = pr.html_url?.match(/ApollosProject\/([^/]+)\/pull\/(\d+)/);
        if (!m) return null;
        return { repo: m[1], number: Number(m[2]) };
      })
      .filter((p): p is PrRef => p != null);

    const [reviews, commitsResult] = await Promise.all([
      buildReviewEntries(
        filterApollosPRs(reviewItems),
        windowStart,
        windowEnd,
        username,
        headers
      ),
      fetchCommitsPushed(username, headers, windowStart, windowEnd, userPrRefs),
    ]);

    // Every PR you authored or reviewed, deduped. This used to be capped at the
    // first 20, which in a busy week meant only authored PRs were ever looked
    // at and every comment left on someone else's PR went uncounted.
    const totalComments = await countPrCommentsInWindow(
      [
        ...(prDetails as Array<{ comments_url?: string }>).map(
          (pr) => pr.comments_url
        ),
        ...reviews.map((r) => r.url),
      ].filter((u): u is string => !!u),
      username,
      windowStart,
      windowEnd,
      headers
    );

    return {
      prs: prDetails,
      reviews,
      comments: totalComments,
      commits_pushed: commitsResult.total,
      reposWithCommits: commitsResult.reposWithCommits,
    };
  } catch (err) {
    // A rate-limited run must not be reported as a quiet zero. These numbers are
    // shown as the day's work and can be written into a saved weekly summary, so
    // "we could not ask" has to surface as an error, not as "you did nothing".
    if (err instanceof SearchBudgetError) throw err;
    if (err instanceof RateLimitExhaustedError) throw err;
    // The batched reads are now the source of these numbers, so a GraphQL
    // failure is the difference between a real count and a zero, not a single
    // unreachable PR.
    if (err instanceof GitHubGraphQLError) throw err;
    return {
      prs: [],
      reviews: [],
      comments: 0,
      commits_pushed: 0,
      reposWithCommits: [],
    };
  }
}

function categorizePRs<T extends { merged_at?: string | null; state?: string }>(
  prs: T[],
  windowStart: Date,
  windowEnd: Date
): { merged: T[]; open: T[] } {
  // The candidate search has no upper bound on date, so a backfilled week would
  // otherwise count PRs merged after that week had already ended.
  const merged = prs.filter((pr) => {
    if (!pr.merged_at) return false;
    const at = new Date(pr.merged_at);
    return at >= windowStart && at <= windowEnd;
  });
  const open = prs.filter((pr) => pr.state === "open" && !pr.merged_at);
  return { merged, open };
}

function groupPRsByRepo(
  prs: Array<{ html_url?: string; url?: string; repo?: string | null }>
) {
  const grouped: Record<string, unknown[]> = {};
  for (const pr of prs) {
    const m = (pr.html_url ?? pr.url)?.match(/ApollosProject\/([^/]+)/);
    const repo = pr.repo ?? (m ? m[1] : "unknown");
    if (!grouped[repo]) grouped[repo] = [];
    grouped[repo].push(pr);
  }
  return grouped;
}

function buildTerminalOutput(
  linearData: {
    completedIssues: unknown[];
    completedProjects: unknown[];
    workedOnIssues: unknown[];
    createdIssues: unknown[];
    commentedIssues: unknown[];
  },
  githubData: {
    prs: unknown[];
    reviews: ReviewEntry[];
    commits_pushed?: number;
  },
  checkIns: CheckIn[],
  prCategories: {
    merged: Array<{
      additions?: number;
      deletions?: number;
      changed_files?: number;
    }>;
  },
  repos: string[],
  volume: { lines_added: number; lines_deleted: number; files_changed: number },
  medianLatency: number | null
): string {
  let out = "\n╔══════════════════════════════════════════════════════════╗\n";
  out += "║     Weekly Work Summary                                  ║\n";
  out += "╚══════════════════════════════════════════════════════════╝\n\n";

  out += "📊 Stats:\n\n";
  out += `  • PRs merged: ${prCategories.merged.length}\n`;
  out += `  • PR reviews: ${githubData.reviews.length}\n`;
  out += `  • Commits pushed: ${githubData.commits_pushed ?? 0}\n`;
  out += `  • Code volume: +${volume.lines_added} / -${volume.lines_deleted} (${volume.files_changed} files)\n`;
  out += `  • Median review latency (working hours): ${medianLatency != null ? `${medianLatency}h` : "—"}\n`;
  out += `  • Linear issues completed: ${linearData.completedIssues.length}\n`;
  out += `  • Linear projects completed: ${linearData.completedProjects.length}\n`;
  out += `  • Linear issues worked on: ${linearData.workedOnIssues.length}\n`;
  out += `  • Linear issues created: ${linearData.createdIssues.length}\n`;
  out += `  • Linear replies: ${linearData.commentedIssues.length}\n`;
  out += `  • Repos: ${repos.join(", ") || "—"}\n\n`;

  if (checkIns.length > 0) {
    out += "📝 Check-ins:\n\n";
    for (const c of checkIns) {
      out += `  ${c.day}: ${c.content.slice(0, 80)}${c.content.length > 80 ? "..." : ""}\n`;
    }
  }

  return out;
}

export { buildMarkdownSummary } from "./markdown.js";

export function saveWeeklySummary(payload: Payload, outputDir: string): void {
  try {
    if (!existsSync(outputDir)) {
      mkdirSync(outputDir, { recursive: true });
      writeFileSync(join(outputDir, "README.md"), SUMMARY_README, "utf8");
    }
    const weekEnding = payload.meta.week_ending;
    const jsonPath = join(outputDir, `${weekEnding}.json`);
    const mdPath = join(outputDir, `${weekEnding}.md`);

    writeFileSync(jsonPath, JSON.stringify(payload, null, 2), "utf8");
    writeFileSync(mdPath, buildMarkdownSummary(payload), "utf8");

    console.log(
      `\n📁 Saved to ${outputDir}/ (${weekEnding}.json, ${weekEnding}.md)`
    );
  } catch (err) {
    console.error(`⚠️  Could not save summary: ${(err as Error).message}`);
  }
}

/**
 * Cached runSummary for Index loader. Use bust: true when user clicks Refresh.
 */
export async function getCachedRunSummary(
  options: {
    todayMode: boolean;
    yesterdayMode?: boolean;
    weekEnding?: string;
    checkInsText: string;
    outputDir: string | null;
    /** When capturing a snapshot, bound the window from the prior capture. */
    forCapture?: boolean;
  } & { bust?: boolean }
): Promise<RunSummaryResult> {
  const { bust, forCapture, ...opts } = options;
  const latest = opts.todayMode ? getMostRecentSnapshot() : null;
  const key = opts.weekEnding
    ? `index:week:${opts.weekEnding}`
    : opts.yesterdayMode
      ? "index:yesterday"
      : opts.todayMode
        ? `index:today:${forCapture ? "capture:" : ""}${latest?.payload.meta.generated_at ?? "none"}`
        : "index:weekly";

  const cached = !bust && (dataCache.get(key) as RunSummaryResult | undefined);
  if (cached) return cached;

  const result = await runSummary({ ...opts, forCapture });
  dataCache.set(key, result);
  return result;
}

export async function runSummary(options: {
  todayMode: boolean;
  yesterdayMode?: boolean;
  /** Friday week-ending date (YYYY-MM-DD) for backfilling a past week */
  weekEnding?: string;
  checkInsText: string;
  outputDir: string | null;
  /** Capture path: window starts at the previous day's capture. */
  forCapture?: boolean;
}): Promise<RunSummaryResult> {
  const {
    todayMode,
    yesterdayMode = false,
    weekEnding: weekEndingOpt,
    checkInsText,
    forCapture = false,
  } = options;

  let windowStart: Date;
  let windowEnd: Date;
  let weekEnding: string;

  if (weekEndingOpt) {
    if (todayMode || yesterdayMode) {
      throw new Error("Cannot combine --week with --today or --yesterday");
    }
    const window = getWindowForWeekEnding(weekEndingOpt);
    windowStart = window.windowStart;
    windowEnd = window.windowEnd;
    weekEnding = weekEndingOpt;
  } else {
    const now = new Date();
    if (todayMode) {
      const window = resolveTodayWindow(now, { forCapture });
      windowStart = window.windowStart;
      windowEnd = window.windowEnd;
    } else {
      windowStart = getWindowStart(now, todayMode, yesterdayMode);
      windowEnd = getWindowEnd(now, todayMode, yesterdayMode);
    }
    // Use Friday of the week (not UTC date) so filenames stay consistent across timezones
    const refDate = yesterdayMode
      ? (() => {
          const d = new Date(now);
          d.setDate(now.getDate() - 1);
          return d;
        })()
      : now;
    const weekStart = getWindowStart(refDate, false);
    const fridayOfWeek = new Date(weekStart);
    fridayOfWeek.setDate(weekStart.getDate() + 6);
    weekEnding = `${fridayOfWeek.getFullYear()}-${String(fridayOfWeek.getMonth() + 1).padStart(2, "0")}-${String(fridayOfWeek.getDate()).padStart(2, "0")}`;
  }

  const windowStartISO = windowStart.toISOString();
  const windowEndISO = windowEnd.toISOString();

  const refusalsBefore = coreRefusalCount();
  const gapsBefore = toleratedGapCount();

  const [linearData, githubData] = await Promise.all([
    fetchLinearData(windowStart, windowEnd, windowStartISO, windowEndISO),
    fetchGitHubData(windowStart, windowStartISO, windowEnd),
  ]);

  // The per-PR fans swallow their own fetch errors so one bad PR cannot sink a
  // summary, which means a spent budget reaches here as zeros rather than as a
  // failure. A summary built on refused requests is wrong in the one direction
  // that matters — it under-reports work and would be saved as fact — so fail
  // the run instead of returning it.
  if (coreRefusalCount() > refusalsBefore) {
    const budget = peekCoreBudget();
    throw new RateLimitExhaustedError(
      budget?.resetAt ?? Date.now(),
      budget?.limit ?? 5000
    );
  }

  // Same reasoning for the batched reads: a tolerated gap means some PRs went
  // unanswered, so every count derived from them is short by an unknown amount.
  const gaps = toleratedGapCount() - gapsBefore;
  if (gaps > 0) {
    throw new GitHubGraphQLError(
      `${gaps} PR${gaps === 1 ? "" : "s"} could not be read; counts would be short`
    );
  }

  const checkIns = parseCheckIns(checkInsText);
  const prCategories = categorizePRs(
    githubData.prs as Array<{
      merged_at?: string | null;
      state?: string;
      additions?: number;
      deletions?: number;
      changed_files?: number;
    }>,
    windowStart,
    windowEnd
  );
  // PRs/reviews plus any tracked repo where you pushed commits (commit-only work)
  const prsAndReviews = [...githubData.prs, ...githubData.reviews] as Array<{
    html_url?: string;
    url?: string;
    repo?: string | null;
  }>;
  const prsByRepo = groupPRsByRepo(prsAndReviews);
  const commitRepos = githubData.reposWithCommits ?? [];
  const repos = [
    ...new Set([...Object.keys(prsByRepo), ...commitRepos]),
  ].sort();

  const volume = sumVolume(prCategories.merged);
  const latencyValues = githubData.reviews
    .map((r: ReviewEntry) => r.latency_hours)
    .filter((h): h is number => typeof h === "number");
  const medianLatency = median(latencyValues);

  const stats: Stats = {
    prs_merged: prCategories.merged.length,
    prs_total: githubData.prs.length,
    pr_reviews: githubData.reviews.length,
    pr_comments: githubData.comments,
    commits_pushed: githubData.commits_pushed ?? 0,
    linear_completed:
      linearData.completedIssues.length + linearData.completedProjects.length,
    linear_projects_completed: linearData.completedProjects.length,
    linear_worked_on: linearData.workedOnIssues.length,
    linear_issues_created: linearData.createdIssues.length,
    linear_comments: linearData.commentedIssues.length,
    repos,
    lines_added: volume.lines_added,
    lines_deleted: volume.lines_deleted,
    files_changed: volume.files_changed,
    median_review_latency_hours: medianLatency,
  };

  const terminalOutput = buildTerminalOutput(
    linearData,
    githubData,
    checkIns,
    prCategories,
    repos,
    volume,
    medianLatency
  );

  const payload: Payload = {
    meta: {
      generated_at: new Date().toISOString(),
      window_start: windowStartISO,
      window_end: windowEndISO,
      week_ending: weekEnding,
      source_of_truth:
        "End-of-year review and career narrative. Document leadership, ownership, mentoring, cross-team work, and technical impact.",
    },
    stats,
    linear: {
      completed_issues: linearData.completedIssues.map(
        (i: LinearIssueNode) => ({
          identifier: i.identifier ?? "",
          title: i.title ?? "",
          project: i.project?.name ?? null,
          url: i.url ?? null,
          completedAt: i.completedAt ?? null,
          state: i.state?.name ?? i.state?.type ?? null,
        })
      ),
      completed_projects: linearData.completedProjects.map((p) => {
        const scope = Math.round(p.scope ?? 0);
        return {
          identifier: "Project",
          title: p.name ?? "",
          project: p.name ?? null,
          url: p.url ?? null,
          completedAt: p.completedAt ?? null,
          state: p.status?.name ?? p.status?.type ?? null,
          description: p.description ?? null,
          startedAt: p.startedAt ?? p.startDate ?? null,
          targetDate: p.targetDate ?? null,
          lead: p.lead?.name ?? null,
          issue_count: scope,
          completed_issue_count: Math.round(scope * (p.progress ?? 0)),
        };
      }),
      worked_on_issues: linearData.workedOnIssues.map((i: LinearIssueNode) => ({
        identifier: i.identifier ?? "",
        title: i.title ?? "",
        project: i.project?.name ?? null,
        url: i.url ?? null,
        completedAt: i.completedAt ?? null,
        state: i.state?.name ?? i.state?.type ?? null,
      })),
      created_issues: linearData.createdIssues.map((i: LinearIssueNode) => ({
        identifier: i.identifier ?? "",
        title: i.title ?? "",
        project: i.project?.name ?? null,
        url: i.url ?? null,
        createdAt: i.createdAt ?? null,
        state: i.state?.name ?? i.state?.type ?? null,
      })),
      commented_issues: linearData.commentedIssues,
    },
    github: {
      merged_prs: prCategories.merged.map(
        (pr: {
          title?: string;
          html_url?: string;
          merged_at?: string | null;
          additions?: number;
          deletions?: number;
          changed_files?: number;
        }) => {
          const m = pr.html_url?.match(/ApollosProject\/([^/]+)/);
          return {
            title: pr.title ?? "",
            url: pr.html_url ?? "",
            repo: m ? m[1] : null,
            merged_at: pr.merged_at ?? null,
            additions: pr.additions ?? 0,
            deletions: pr.deletions ?? 0,
            changed_files: pr.changed_files ?? 0,
          };
        }
      ),
      open_prs: prCategories.open.map(
        (pr: { title?: string; html_url?: string; state?: string | null }) => {
          const m = pr.html_url?.match(/ApollosProject\/([^/]+)/);
          return {
            title: pr.title ?? "",
            url: pr.html_url ?? "",
            repo: m ? m[1] : null,
            state: pr.state ?? null,
          };
        }
      ),
      reviews: githubData.reviews as ReviewEntry[],
    },
    check_ins: checkIns,
    terminal_output: terminalOutput,
    formatted_output: null,
  };

  return {
    payload,
    terminalOutput,
    formattedOutput: null,
  };
}
